GET http://localhost:8080/api/users
Accept: application/json

###
POST http://localhost:8080/api/registration/save
Content-Type: application/json

{
  "name": "habib123",
  "email": "xyz@gmail.com",
  "phone": "3224323",
  "address": "Bashundhara123"
}

###
