GET http://localhost:8080/api/users
Accept: application/json

###
GET http://localhost:8080/api/users/1
Accept: application/json

###
POST http://localhost:8080/api/users/register
Content-Type: application/json

{
  "name": "Ashiq",
  "username": "Ashiq123",
  "email": "abc@gmail.com",
  "phone": "3224323345",
  "address": "Bashundhara123",
  "password": "1234567$a"
}

###
DELETE http://localhost:8080/api/users/1
Accept: application/json

###
PUT http://localhost:8080/api/users/1
Content-Type: application/json

{
  "name": "habib",
  "username": "habiasfb",
  "email": "xyzasfaf@gmail.com",
  "phone": "3224323123",
  "address": "Bashundhara123",
  "password": "abCD*#/-1"
}

